name: Bug Report
description: Report a problem with the agent
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Agent output
      description: Paste the relevant terminal output (redact API keys and personal info)
      render: shell
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: e.g. v20.11.0
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. macOS 14, Ubuntu 22.04
    validations:
      required: false
